name: auth_graphql
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc:
  shared_preferences:
  ferry:
  gql_http_link:
  gql_code_builder_serializers:
  ferry_flutter:
  get_it:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  ferry_generator:
  build_runner:
flutter:
  uses-material-design: true
